export const REPORT_TYPES = {
  SALES_REGISTER: 'SALES_REGISTER',
  PURCHASE_REGISTER: 'PURCHASE_REGISTER',
  INVENTORY_SNAPSHOT: 'INVENTORY_SNAPSHOT',
  OUTSTANDING_RECEIVABLES: 'OUTSTANDING_RECEIVABLES'
}

export const UPLOAD_STATUS = {
  UPLOADED: 'UPLOADED',
  NEEDS_TEMPLATE_SELECTION: 'NEEDS_TEMPLATE_SELECTION',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_PASSED: 'VALIDATION_PASSED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
}

export const INSIGHT_SEVERITY = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
}
